apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-wordpress
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: wordpress
  hostPath:
    path: /data
    type: Directory