apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 30036
      targetPort: 3306
  selector:
    app: mysql