apiVersion: v1
kind: Service
metadata:
  name: svc-frontend-wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
    - targetPort: 
      port:
      nodePort: 